# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Website CI/CD

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Publish code"
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PORT: ${{ secrets.PORT }}
          PASS: ${{ secrets.PASS }}
        with:
          host: $HOST
          username: $USER_NAME
          password: geofrey7543
          port: 22
          script: |
            cd /var/www
            echo geofrey7543 | sudo -S rm -r imprintdev
            echo geofrey7543 | sudo -S git clone https://github.com/GeofreyMuindeMunguti/imprintdev/
            echo geofrey7543 | sudo -S systemctl reload nginx
