# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Website CI/CD

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Publish code"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www
            echo ${{ secrets.PASS }} | sudo -S rm -r imprintdev
            echo ${{ secrets.PASS }} | sudo -S git clone https://github.com/GeofreyMuindeMunguti/imprintdev/
            echo ${{ secrets.PASS }} | sudo -S systemctl reload nginx
